name: CI/CD for Kubernetes Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}


  #Step 1: Checkout repository
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
  #Step 2: Login to Azure
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  # Step 3: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ env.REGISTRY_NAME }}

  # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGISTRY_URL }}/myapp:${{ github.sha }} .

    # Step 6: Push Docker image to ACR
    - name: Push Docker image to ACR
      run: |
        docker push ${{ env.REGISTRY_URL }}/myapp:${{ github.sha }}
    
    #step:
    - uses: azure/aks-set-context@v3
      with:
        resource-group: 'deakinuni'
        cluster-name: '${{ secrets.AKS_CLUSTER_NAME }}'


    - uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          scripts/deploy.yaml
        images: '${{ env.REGISTRY_URL }}/myapp:${{ github.sha }}'
