name: CI/CD for Kubernetes Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

  #step1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
      # Step 2: Install Azure CLI 
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash


    # Step 3: Login to Azure
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 4: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name task8

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t task8.azurecr.io/my-app:${{ github.sha }} .

    # Step 6: Push Docker image to ACR
    - name: Push Docker image to ACR
      run: |
        docker push task8.azurecr.io/my-app:${{ github.sha }}

    # Step 7: Deploy to AKS
    - name: Deploy to AKS
      run: |
        kubectl set image deployment/myapp myapp=task8.azurecr.io/my-app:${{ github.sha }}
      env:
        KUBECONFIG: ${{ secrets.AKS_KUBECONFIG }}
